services:
  neo4j:
    image: neo4j:5.8.0
    container_name: neo4j
    ports:
      - "7474:7474"   # Neo4j browser
      - "7687:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/neo4j-secret
    volumes:
      - neo4j_data:/data

  app:
    image: neo4j-graph-db-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
